
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///internet
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
